qa_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from question_answer import views, forms
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/register/', views.register, ),
    url(r'^users/login/', auth_views.login, {'authentication_form': forms.LoginForm,}),
    url(r'^questions/', include('question_answer.urls', namespace="questions")),
]

question_answer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [url(r'^$', views.index, name="index"),
        url(r'^(?P<pk>[0-9]+)/$', views.detail, name="detail"),
        url(r'^(?P<pk>[0-9]+)/up/$', views.voteUp, name="up"),
        url(r'^(?P<pk>[0-9]+)/down/$', views.voteDown, name="down"),
        url(r'^answer/(?P<pk>[0-9]+)/up/$', views.answerVoteUp, name="aUp"),
        url(r'^answer/(?P<pk>[0-9]+)/down/$', views.answerVoteDown, name="aDown"),
        url(r'^ask/$', views.ask, name="ask"),
        url(r'^tag/(?P<pk>[0-9]+)/$', views.by_tag, name="tag"),
        ]

question_answer/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    tag_name = models.CharField(max_length=16)
#TODO:
#make tags clickable

class Question(models.Model):
# Question model desc.
    question_name = models.CharField(max_length=200)
    question_text = models.CharField(max_length=512)
    score = models.IntegerField(default=0)
    pub_date = models.DateTimeField()
    tags = models.ManyToManyField(Tag)
#TODO:
#user
#comments
    def __string__ (self):
        return self.question_name

class Answer(models.Model):
# Answer model desc.
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=512)
    score = models.IntegerField(default=0)
    pub_date = models.DateTimeField()
#TODO:
#user
#comments

question_answer/forms.py
from django.forms import ModelForm, CharField
from .models import Question
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit

class QuestionForm(ModelForm):

    class Meta:
        model = Question
        fields = ['question_name', 'question_text', 'tags']
   #     widgets = {'tags': CharField}

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CreateUserForm,self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
                'username',
                'password1',
                'password2',
                Submit('register', 'Register', css_class='btn-default'),
            )

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm,self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
                'username',
                'password',
                Submit('login', 'Login', css_class='btn-default'),
            )

question_answer/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Tag, Answer
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import QuestionForm, CreateUserForm
from django.utils import timezone
# Create your views here.

def index (request):
    question_list = Question.objects.order_by('-score')[:10]
    template = loader.get_template("question_answer/index.html")
    context = RequestContext(request, {'question_list': question_list,})
    return HttpResponse(template.render(context))

def detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == "POST":
        answer = Answer()
        answer.answer_text = request.POST["answer_text"]
        answer.pub_date = timezone.now()
        answer.question_id = question.id
        answer.save()
    else:
        pass
    template = loader.get_template("question_answer/question.html")
    context = RequestContext(request, {'question': question,})
    return HttpResponse(template.render(context))

def voteUp(request, pk):
    question = get_object_or_404(Question, pk=pk)
    question.score = question.score + 1
    question.save()
    return HttpResponse("okay")

def voteDown(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if question.score > 0:
        question.score = question.score - 1
        question.save()
    return HttpResponse("okay")

def answerVoteUp(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    answer.score = answer.score + 1
    answer.save()
    return HttpResponse("okay")

def answerVoteDown(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    if answer.score > 0:
        answer.score = answer.score - 1
        answer.save()
    return HttpResponse("okay")


def ask(request):
    if request.method == "POST":

        new_q = Question()
        new_q.question_name = request.POST['QuestionName']
        new_q.question_text = request.POST['QuestionText']
        new_q.pub_date = timezone.now()
        new_q.save()
        tag_strings = request.POST['TagList']
        tag_strings = tag_strings.split(' ')

        tag_list = Tag.objects.all()
        for tag in tag_strings:
            t, created = Tag.objects.get_or_create(tag_name=tag)
            new_q.tags.add(t)

        new_q.save()

        return HttpResponseRedirect('/questions/')
    else:
        pass
    return render(request, 'question_answer/ask.html')

def by_tag (request, pk):
    tag = get_object_or_404(Tag, pk=pk)

    question_list = tag.question_set.all()
    template = loader.get_template("question_answer/index.html")
    context = RequestContext(request, {'question_list': question_list,})
    return HttpResponse(template.render(context))

def register(request):
    form = CreateUserForm()
    template = loader.get_template("registration/register.html")
    context = RequestContext(request, {'form':form,})
    return HttpResponse(template.render(context))

question_answer/templates/question_answer/ask.html
{% extends 'question_answer/base.html' %}

{% block title %}Ask A Question{% endblock %}

{% block content %}

<form action="{% url 'questions:ask' %}" method="post" >
    {% csrf_token %}
                <div class="form-group">
                        <label for="QuestionName">Question Name?</label>
                        <input id="QuestionName" class="form-control" name="QuestionName">
                    </div>
                    <div class="form-group">
                        <label for="QuestionText">Ask your question:</label>
                        <textarea id="QuestionText" name="QuestionText" class="form-control" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="TagList">Question Tags</label>
                        <input id="TagList" class="form-control" name="TagList">
                        <p>Add a space separated list of tags that apply to your question. Ex "tag tagtag"</p>
                    </div>
    <button type="submit" class="btn btn-default">Ask</button>
</form>

{% endblock %}

question_answer/templates/question_answer/content.html
{% extends 'question_answer/base.html' %}

{% load staticfiles %}

{% block title %}<!-- title goes here -->{% endblock %}

{% block content %}

<!-- put new content here  -->

{% endblock %}

question_answer/templates/question_answer/index.html
{% extends 'question_answer/base.html' %}

{% block title %}Questions and Answers {% endblock %}

{% block content %}

{% for question in question_list %}
        <div class="row">
            <div class="col-md-3 text-center">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <h2>{{ question.score }}</h2>
                        <p>Score</p>
                    </div>
                    <div class="col-md-6 text-center">
                        <h2>{{ question.answer_set.count }}</h2>
                        <p>Answers</p>
                    </div>
                </div>
            </div>

            <div class="col-md-9">
                <h3><a href="{% url 'questions:detail' question.id %}">{{ question.question_name }}</a></h3>
                <p>{{ question.question_text }}</p>
                {% for tag in question.tags.all %}
                <a href="{% url 'questions:tag' tag.id %}" class="label label-info">{{ tag.tag_name }}</a>
                {% endfor %}
            </div>
        </div>
        <hr>
{% endfor %}
{% endblock %}

question_answer/templates/question_answer/question.html
{% extends 'question_answer/base.html' %}

{% load staticfiles %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}

<!-- display the question title -->
<div class="row">
    <div class="col-md-2 text-center">
        <span id="upvote" class="glyphicon glyphicon-chevron-up upvote"></span>
        <h4 id="qScore">{{ question.score }}</h4>
        <p>Score</p>
        <span id="downvote" class="glyphicon glyphicon-chevron-down downvote"></span>
    </div>
    <div class="col-md-10">
        <h2>{{ question.question_name }}</h2>
        <hr>
        <p>{{ question.question_text }}</p>
    </div>
</div>
{% for answer in question.answer_set.all %}
<div id="answer-{{ answer.id }}" class="row">
    <hr>
    <div class="col-md-2 text-center">
        <span class="glyphicon glyphicon-chevron-up upvote"></span>
        <h4>{{ answer.score }}</h4>
        <p>Score</p>
        <span class="glyphicon glyphicon-chevron-down downvote"></span>
    </div>
    <div class="col-md-10">
        <p>{{ answer.answer_text }}</p>
    </div>
</div>
{% endfor %}

<form action="{% url 'questions:detail' question.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="answer_text">Comment:</label>
        <textarea id="answer_text" name='answer_text' class="form-control" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>


{% endblock %}

{% block scripts %}
<script src="{% static 'questions/js/voting.js' %}"></script>
{% endblock %}